[default]
extend-ignore-re = [
  ".*_nd",
  "pn_*",
  "EDE_*",
  "PN",
  "Josh Aas",
  "hel.*lo",
  "mis-*",
  "thr",
  "ture dat",
  # XXX TBD encrypter -> encryptor - XXX TBD ???
  ".*Encrypter.*",
  ".*encrypter.*",
  # XXX TODO RESOLVE IF & WHEN POSSIBLE:
  "negotation",
  "Negotation",
  "seperately",
  "succesfully",
]

[files]
extend-exclude = [
  # ---
  "*.cert",
  "*.chain",
  "*.fullchain",
  "*.pem",
  "*.svg",
  "rfc*.json",
  "website/templates/macros.html",
]
