[package]
name = "bogo"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { workspace = true }
env_logger = { workspace = true }
# WITH ADAPTED MAIN PACKAGE NAME for this fork
rustls = { package = "portable-rustls", path = "../rustls", features = ["std", "aws_lc_rs", "ring", "tls12"] }
rustls-post-quantum = { path = "../rustls-post-quantum", optional = true }

[features]
default = []
post-quantum = ["dep:rustls-post-quantum"]
fips = ["rustls/fips"]
