[package]
name = "rustls-examples"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0 OR ISC OR MIT"
description = "Rustls example code and tests."
publish = false

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"], optional = true }
clap = { version = "4", features = ["derive"] }
env_logger = "0.10" # 0.11 requires 1.71 MSRV even as a dev-dep (due to manifest features)
hickory-resolver = { version = "=0.25.0-alpha.3", features = ["dns-over-https-rustls", "webpki-roots"] }
log = { version = "0.4.4" }
mio = { version = "0.8", features = ["net", "os-poll"] }
rcgen = { version = "0.13", features = ["pem", "aws_lc_rs"], default-features = false }
rustls = { path = "../rustls", features = [ "logging" ]}
serde = "1.0"
serde_derive = "1.0"
tokio = { version = "1.34.0", features = ["io-util", "macros", "net", "rt"]}
webpki-roots = "0.26"
# XXX TBD MOVE THESE ADDED ITEM(S) - ???
# XXX TBD USE XXX XXX XXX FROM GITHUB WITH @brodycj XXX PROPOSAL FOR NOW - `portable-atomic` PR REF: https://github.com/taiki-e/portable-atomic/pull/195
# XXX TODO USE PUBLISHED CRATE ONCE @brodycj XXX PROPOSAL IS ACCEPTED
portable-atomic-util = { version = "0.2.3", default-features = false, features = ["alloc"], optional = true, git = "https://github.com/brodycj/portable-atomic", branch = "custom-unsized-coercions" }

[features]
critical-section = ["portable-atomic-util", "rustls/critical-section"]
