name: rustls

permissions:
  contents: read

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 18 * * *'

jobs:
  # XXX TODO REPLACE THIS HACKED-UP PR 2088 JOB WITH WORKING BUILD / TEST UPDATES WITH NEW FEATURE OPTIONS
  pr-2088-specific-build-testing:
    name: ABC Build & test for PR 2088 - want CI to test this first for PR 2088
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: cargo build (debug; rustls package with no feature options specified)
        run: cargo build --locked --package rustls

      - name: cargo test (debug; rustls package with no feature options specified)
        run: cargo test --package rustls
        env:
          RUST_BACKTRACE: 1

      - name: cargo build (debug; rustls package with only aws-lc-rs feature enabled)
        run: cargo build --locked --no-default-features --features aws-lc-rs --package rustls

      - name: cargo test (debug; rustls package with only aws-lc-rs,std features enabled)
        run: cargo test --no-default-features --features aws-lc-rs,std --package rustls

      - name: cargo build (debug; rustls package with the critical-section feature enabled)
        run: cargo build --locked --features critical-section --package rustls

      - name: cargo test (debug; rustls package with the critical-section feature enabled)
        run: cargo test --features critical-section --package rustls

      - name: cargo build (debug; rustls package with only aws-lc-rs,critical-section features enabled)
        run: cargo build --locked --no-default-features --features aws-lc-rs,critical-section --package rustls

      - name: cargo test (debug; rustls package with only aws-lc-rs,critical-section,std features enabled)
        run: cargo test --no-default-features --features aws-lc-rs,critical-section,std --package rustls

      - name: cargo build (debug; rustls package with withrcalias & critical-section features enabled)
        run: cargo build --locked --features withrcalias,critical-section --package rustls

      - name: cargo test (debug; rustls package with withrcalias & critical-section features enabled)
        run: cargo test --features withrcalias,critical-section --package rustls

      - name: cargo build (debug; rustls package with the withrcalias feature enabled)
        run: cargo build --locked --features withrcalias --package rustls

      - name: cargo test (debug; rustls package with the withrcalias feature enabled)
        run: cargo test --features withrcalias --package rustls

  # XXX FIX & RESTORE:
  # build:
  #   name: Build+test
  #   runs-on: ${{ matrix.os }}
  #   ...

  # XXX FIX & RESTORE:
  # msrv:
  #   name: MSRV
  #   ...

  bogo:
    name: BoGo test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install golang toolchain
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: Run test suite (ring)
        working-directory: bogo
        run: ./runme
        env:
          BOGO_SHIM_PROVIDER: ring

      - name: Run test suite (aws-lc-rs)
        working-directory: bogo
        run: ./runme
        env:
          BOGO_SHIM_PROVIDER: aws-lc-rs

      - name: Run test suite (aws-lc-rs-fips)
        working-directory: bogo
        run: ./runme
        env:
          BOGO_SHIM_PROVIDER: aws-lc-rs-fips

  # XXX FIX & RESTORE:
  # fuzz:
  #   ...

  # XXX FIX & RESTORE:
  # benchmarks:
  #   ...

  # XXX FIX & RESTORE:
  # docs:
  #   ...

  # XXX FIX & RESTORE:
  # coverage:
  #   ...

  minver:
    name: Check minimum versions of direct dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo-minimal-versions
        uses: taiki-e/install-action@cargo-minimal-versions

      # cargo-minimal-versions requires cargo-hack
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Check direct-minimal-versions
        run: cargo minimal-versions --direct --ignore-private check
        working-directory: rustls/

  cross:
    name: cross-target testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # 32-bit Android (Linux) targets:
          - armv7-linux-androideabi
          - i686-linux-android
          - thumbv7neon-linux-androideabi
          # Other standard 32-bit (Linux) targets (SKIP bindgen for i686 only)
          - i586-unknown-linux-gnu
          - i686-unknown-linux-gnu
          # exotic Linux targets:
          - riscv64gc-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          # additional target(s):
          # NOTE: This could have some overlap with 64-bit ARM-style CPU on macOS CI host;
          # may have similar ARM-style CPU overlap with standard Windows & possibly Linux in the future
          - aarch64-linux-android
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross (cross-rs) from GitHub
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Install bindgen feature & CLI for aws-lc-sys (as needed for many cross targets)
        if: ${{ matrix.target != 'i686-unknown-linux-gnu' }}
        run: cargo add --dev --features bindgen aws-lc-sys --package rustls --verbose && cargo install bindgen-cli --verbose
      - run: cross test --package rustls --target ${{ matrix.target }}

  cross-with-rc-alias:
    # XXX TBD FIND A WAY TO TEST WITH THIS KIND OF EMBEDDED TARGET
    name: cross-target build testing with RC alias
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # 32-bit target with no atomic ptr
          - thumbv6m-none-eabi
          # XXX TBD other targets to test this build on ???
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross (cross-rs) from GitHub
        run: cargo install cross --git https://github.com/cross-rs/cross
      # XXX TODO FIND WAY TO GET BUILD WORKING WITH BUILT-IN PROVIDERS
      - run: cross build --no-default-features --features critical-section,custom-provider,withrcalias --package rustls --target ${{ matrix.target }}
      # XXX TBD TRY BUILDING WITH SOME OTHER FEATURES - ???
      # XXX TBD FIND A WAY TO TEST (AS XXX TBD NOTED ABOVE AS WELL)

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check formatting (connect-tests workspace)
        run: cargo fmt --all --manifest-path=connect-tests/Cargo.toml -- --check
      - name: Check formatting (fuzz workspace)
        run: cargo fmt --all --manifest-path=fuzz/Cargo.toml -- --check

  format-unstable:
    name: Format (unstable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install rust nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2024-02-21
      - name: Check formatting (unstable)
        run: cargo fmt --all -- --check --config-path .rustfmt.unstable.toml
        continue-on-error: true
      - name: Check formatting (unstable, connect-tests workspace)
        run: cargo fmt --all --manifest-path=connect-tests/Cargo.toml -- --check --config-path .rustfmt.unstable.toml
        continue-on-error: true
      - name: Check formatting (unstable, fuzz workspace)
        run: cargo fmt --all --manifest-path=fuzz/Cargo.toml -- --check --config-path .rustfmt.unstable.toml
        continue-on-error: true

  # XXX FIX & RESTORE:
  # clippy:
  #   ...
  #
  # clippy-nightly:
  #   ...

  check-external-types:
    name: Validate external types appearing in public API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-05-01
          # ^ sync with https://github.com/awslabs/cargo-check-external-types/blob/main/rust-toolchain.toml
      - run: cargo install --locked cargo-check-external-types
      - name: run cargo-check-external-types for rustls/
        working-directory: rustls/
        run: cargo check-external-types

  openssl-tests:
    name: Run openssl-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: openssl version
        run: openssl version

      - name: cargo test (in openssl-tests/)
        working-directory: openssl-tests/
        run: cargo test --locked -- --include-ignored
        env:
          RUST_BACKTRACE: 1
