name: documentation

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    # GONE FROM THIS FORK:
    # branches:
    #   - main
  schedule:
    - cron: '0 18 * * *'

jobs:
  generate:
    name: Generate pre-release documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      # GONE FROM THIS FORK:
      # - name: Install zola
      # ...

      - name: Generate version information
        run: |
          echo >tag.html \
            "<script>var version = document.querySelector(\"span.version\");" \
            "version.innerHTML += \"<br>(pre-release docs from <tt>$GITHUB_REF</tt>)\";" \
            "version.title = \"commit $GITHUB_SHA\";" \
            "</script>"

      - name: cargo doc
        # keep features in sync with Cargo.toml `[package.metadata.docs.rs]` section
        run: cargo doc --locked --features aws_lc_rs,std,tls12,read_buf,ring --no-deps --package portable-rustls
        env:
          RUSTDOCFLAGS: -Dwarnings --cfg=docsrs --html-after-content tag.html

      # GONE FROM THIS FORK: Generate other pages for website (etc.)

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # SKIP IN THIS FORK
    # if: github.repository == 'rustls/rustls'
    if: false
    needs: generate
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
